### PR TITLE
export loki logs to minio at the end of each case

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: yeya24 <yb532204897@gmail.com>

### What problem does this PR solve? 

1. export loki logs to minio at the end of each case
2. add a bank iochaos template and workflow

### Check List 

Tests 

 - Unit test
 - E2E test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has Go code change
 - Has CI related scripts change
 - Has Terraform scripts change

Side effects

 - Breaking backward compatibility

Related changes

 - Need to update the documentation

### Does this PR introduce a user-facing change?:

```release-note
NONE
```

### CODE REVIEW

**Comment by yeya24** [comment]
The result is that now you can download the logs tar archive directly from argo artifacts page.
image

**Comment by zhouqiang-cl** [comment]
Can we default add collect log step

**Comment by yeya24** [comment]
> Can we default add collect log step

I already added this to the template so this will be the last step

**Comment by zhouqiang-cl** [comment]
in artifacts. seems some log is missing(pd log in empty)

**Pull request merged**
