### PR TITLE
Remove unused go mod dependency

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: yeya24 <yb532204897@gmail.com>

### What problem does this PR solve? 

In master branch I tried `go mod tidy`

```
➜  tipocket git:(master) go mod tidy
go: launchpad.net/gocheck@v0.0.0-20140225173054-000000000087: bzr branch --use-existing-dir -- https://launchpad.net/~niemeyer/gocheck/trunk . in /Users/yeya24/go/pkg/mod/cache/vcs/f46ce2ae80d31f9b0a29099baa203e3b6d269dace4e5357a2cf74bd109e13339: exec: "bzr": executable file not found in $PATH
```

Seems some of the dependencies are not needed and I remove them in this pr.

### Check List 

Tests 

 - Unit test
 - E2E test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has Go code change
 - Has CI related scripts change
 - Has Terraform scripts change

Side effects

 - Breaking backward compatibility

Related changes

 - Need to update the documentation

### Does this PR introduce a user-facing change?:

```release-note
NONE
```

### CODE REVIEW

**Comment by mapleFU** [comment]
Why does this pr introduce so many records in go.sum?

**Comment by yeya24** [comment]
> Why does this pr introduce so many records in go.sum?

I am not sure. But I guess since we lack this go mod check in tipocket, the go.sum is not correct before.

**Comment by mapleFU** [comment]
After delete go.sum and make it, the go.sum shrink. Maybe you could try it.

**Comment by mahjonp** [comment]
> > Why does this pr introduce so many records in go.sum?
> 
> I am not sure. But I guess since we lack this go mod check in tipocket, the go.sum is not correct before.

did you rm go.sum and re-generated it?

**Comment by yeya24** [comment]
Thank you. I have updated it.

**Pull request merged**
