### PR TITLE
Add dockerfile for export-logs template

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: yeya24 <yb532204897@gmail.com>

### Check List 

Tests 

 - Unit test
 - E2E test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has Go code change
 - Has CI related scripts change
 - Has Terraform scripts change

Side effects

 - Breaking backward compatibility

Related changes

 - Need to update the documentation

### Does this PR introduce a user-facing change?:

```release-note
NONE
```

### CODE REVIEW

**Comment by yeya24** [comment]
This PR is not needed anymore, since we may put the log collector into loki itself.

**Comment by zhouqiang-cl** [comment]
So. Close it?

**Comment by yeya24** [comment]
We can still keep it open until the new logs exporting functionality is merged.

**Comment by yeya24** [comment]
Close this since the new log export feature is merged

**Pull request closed without merging**
